### ISSUE TITLE
Activer et configurer le service AppSync sur AWS

### ISSUE THREAD

**Issue by christian970** [mongulu-cm/mah-oum#3]
Le service qui permet d'interfacer un client ou un utilisateur lambda aux services d'Amazone doit être activer et configurer

**Comment by billmetangmo** [comment]
J'ai ajouté le code terraform permettant de créer une API GraphQL sur Appsync en m'inspirant de l'api de l'event app AWS: https://github.com/amazon-archives/aws-mobile-appsync-events-starter-react . 

Il faudra modifier cette API pour nos besoins mais le branchement est fait donc je ferme l'issue.

NB: Si tu veux manipuler l'API GraphQL depuis une interface graphique suis le README. Sinon tu peux le faire directement sur ta console App sync (UI): https://eu-central-1.console.aws.amazon.com/appsync . Tu pourras t'inspirer de mon gist : https://gist.github.com/billmetangmo/fbe722b3c50d47ea9258a1c3a616f5e4 pour les exemples de requêtes.
